### PR TITLE
Update Cypress to 10.8.0, remove deprecated plugins/index.js

### PR DESCRIPTION
**Pull request by tejal-shah**

### CODE REVIEW

**Comment by tejal-shah** [comment]
@kswenson or @eireland , I created this branch in CODAP V3 to update the cypress version, remove the deprecated plugins/index.js file and move the code coverage to cypress.config.ts. But when doing `npm install` , the following error is thrown:
```
**ERROR** Failed to apply patch for package react-data-grid at path
  
    node_modules/react-data-grid

  This error was caused because react-data-grid has changed since you
  made the patch file for it. This introduced conflicts with your patch,
  just like a merge conflict in Git when separate incompatible changes are
  made to the same piece of code.

  Maybe this means your patch file is no longer necessary, in which case
  hooray! Just delete it!

  Otherwise, you need to generate a new patch file.

  To generate a new one, just repeat the steps you made to generate the first
  one.

  i.e. manually make the appropriate file changes, then run 

    patch-package react-data-grid

  Info:
    Patch file: patches/react-data-grid+7.0.0-beta.15.patch
    Patch was made for version: 7.0.0-beta.15
    Installed version: 7.0.0-beta.19
```
Can one of you help me fix this? Locally I tried removing the file `patches/react-data-grid+7.0.0-beta.15.patch` and it didn't throw this error anymore and worked. But I'm unsure if this will cause problems elsewhere. Please advise.

**Review by kswenson — APPROVED** [review]
👍 LGTM

**Review by eireland — APPROVED** [review]
LGTM

**Comment by kswenson** [comment]
These changes have been addressed in subsequent PRs.

**Pull request closed without merging**
