### PR TITLE
Upgrade to Cypress 13

### PR DESCRIPTION
**Pull request by tejal-shah**

### CODE REVIEW

**Review by kswenson — CHANGES_REQUESTED** [review]
Note the failing tests in the CI build. That's what I ran into when I tried to update to v13.

**Comment by tejal-shah** [comment]
Oh okay. Looking into that now.

**Comment by tejal-shah** [comment]
I finally got these to work @kswenson . It turns out we were running our cypress tests on Electron browser and there are many `click` issues for Cypress 13 on Electron. When I made the switch to Chrome, they all magically disappeared, except for one failure, which I fixed in the adornment tests.

**Review by kswenson — APPROVED** [review]
👍 Looks good!

**Pull request merged**
