### PR TITLE
187057621 add sampler translation strings

### PR DESCRIPTION
**Pull request by eireland**
Adds back The Sampler Measures translation strings that got accidentally removed by one of the builds.

### CODE REVIEW

**Comment by bfinzer** [comment]
When I go back in time in CODAP releases (e.g. build 0680) I find that the Sampler is translated. For example I switch language to Spanish and the Sampler shows up with translated strings. But I don't see those translations in this pull request; i.e. strings.js in es.lproj are all in English. I'm guessing this is not as it should be?

**Review by bfinzer — CHANGES_REQUESTED** [review]
See comment about translation strings not being present.

**Comment by eireland** [comment]
I don't think those keys have been translated which is why they come up as English. If you scroll up to lines 901-918, you will see the keys that have been translated into Spanish.

**Review by bfinzer — APPROVED** [review]
👍🏻LGTM

**Pull request merged**
