### PR TITLE
187319504 add check for multiple numeric y attributes

### PR DESCRIPTION
**Pull request by nstclair-cc**
[PT #187319504 - Add Cypress checks for multiple y-attributes](https://www.pivotaltracker.com/story/show/187319504)

With thanks to Teale for helping to figure out the weirdness in Cypress with the `yplus` behavior, I've added a test for checking multiple numeric y attributes.

### CODE REVIEW

**Review by johnTcrawford — APPROVED** [review]
Looks good. I don't love the use of "cy.wait(500)", but sometimes it's necessary, or at least expedient.

**Comment by nstclair-cc** [comment]
> Looks good. I don't love the use of "cy.wait(500)", but sometimes it's necessary, or at least expedient. (Note: you should probably wait for Kirk's review before Merging.)

Thanks, @johnTcrawford for the review! Yeah, I'm not a big fan of `cy.wait(500)` either, but unfortunately with the drag-and-drop nature of CODAP it's sometimes a necessary evil. :-/

**Review by kswenson — APPROVED** [review]
👍 LGTM

**Comment by nstclair-cc** [comment]
I moved the merge to here: [PR 1209](https://github.com/concord-consortium/codap/pull/1209)

**Pull request closed without merging**
