### PR TITLE
feat: Representation of dataset in case card is hierarchical (PT-188173137)

### PR DESCRIPTION
**Pull request by emcelroy**
[#188173137](https://www.pivotaltracker.com/story/show/188173137)

### CODE REVIEW

**Review by kswenson — APPROVED** [review]
👍 Looks good -- I added a commit which fixes a couple of things, including a latent `DataSet` bug (#1441) which I discovered while reviewing it. There's also a few minor suggestions. Unfortunately, there are now failing cypress tests which seem unrelated to this PR but are now occurring consistently after my commit, so I'm not sure what's going on there, but we'll need to figure it out before merging. 🤔

**Comment by emcelroy** [comment]
> Unfortunately, there are now failing cypress tests which seem unrelated to this PR but are now occurring consistently after my commit, so I'm not sure what's going on there, but we'll need to figure it out before merging. 🤔

The newly added `overflow: hidden` line in free-tile-row.scss was preventing the inspector menu to be hidden in at least some cases, hence the failing tests. Is that style rule important? If so, would something like `overflow-y: hidden` be an option?

**Comment by kswenson** [comment]
> > Unfortunately, there are now failing cypress tests which seem unrelated to this PR but are now occurring consistently after my commit, so I'm not sure what's going on there, but we'll need to figure it out before merging. 🤔
> 
> @kswenson The newly added `overflow: hidden` line in free-tile-row.scss was preventing the inspector menu to be hidden in at least some cases, hence the failing tests. Is that style rule important? If so, would something like `overflow-y: hidden` be an option?

🤦 That makes sense. That should have occurred to me last night. I was trying to fix the problem of the case card overflowing its container, so `overflow-y: hidden` should be fine for now. I suspect I'm going to have to revisit that at some point, but  so be it.

**Comment by emcelroy** [comment]
> 🤦 That makes sense. That should have occurred to me last night. I was trying to fix the problem of the case card overflowing its container, so `overflow-y: hidden` should be fine for now. I suspect I'm going to have to revisit that at some point, but so be it.

I tried `overflow-y` but the tests failed for that, too. So I'm going to leave out any overflow rules for now.

**Pull request merged**
