### PR TITLE
183987088 graph color picker UI

### PR DESCRIPTION
**Pull request by eireland**
This adds the UI for the graph and map color picker for data points.
Included:
- 16 palette color swatches + 1 swatch if user selects from the color input picker.
- More/Less button that shows/hides a color input (using the same color input picker that the case table uses)
- Checkmark on the color swatch when user selects a color.

Note that some of the color selection functionality is present, but the focus of this PR is just to add the UI.

### CODE REVIEW

**Comment by bfinzer** [comment]
I get four warnings when I run this. Please fix.

**Comment by bfinzer** [comment]
I notice that in dragging the point size slider the points respond with animation instead of instantly as they do in main. Instant is better. Please fix or log as separate bug.

**Review by bfinzer — APPROVED** [review]
Looks good. Just fix warnings and figure out whether you can fix the  point size animation bug of log as a PT story.

**Review by kswenson — APPROVED** [review]
👍 LGTM

**Comment by kswenson** [comment]
> 👍 LGTM

Forgot to mention in the comment that the `colorHash` implementation should be changed as described above.

**Pull request merged**
