### PR TITLE
Undo/Redo support

### PR DESCRIPTION
**Pull request by sfentress**

### CODE REVIEW

**Comment by jsandoe** [comment]
Sam,

In preparing for this pull request, I noticed that the commit, f8bfe45,
merged the brand with master, but with build_0298 on master, not the
current head of that branch. I was also concerned to see if I could do
something about the 'one click' commit. So, I made a new branch called
'undo-redo', which takes off from before the merge and I rebased (rather
than merged) that with the current head of master. That actually went
rather well. There was one conflict which was easy to resolve. AND it can
be merged back to master with one click. It has all the changes checked in
so far on the wip-undo-redo branch.

So, I propose to accept the "undo-redo" PR and not this. It does not yet
have any more recent changes you may have to this (wip-undo-redo) branch
but from your description they sounded like they would be relatively small,
so easy to merge over from wip-undo-redo.

What do you think, Sam? Does that sound sensible to you?

Thanks,

Jonathan

**Comment by sfentress** [comment]
D'oh, I merged with master but hadn't pulled.

Since I've got a couple more committed to add, would it be clearer for you
if I just added them before rebasing, rebase, then update this PR?

**Comment by jsandoe** [comment]
Hi Sam,

I am not sure I understand what you are proposing, but I would say you
should do whatever is easiest to get the remaining work committed to either
wip-undo-redo or the new branch I created, "undo-redo". I am sure that it
won't be difficult to merge to master.

Thanks,

Jonathan

**Comment by sfentress** [comment]
Hi @jsandoe, this branch now has the my most recent fixes, and is rebased cleanly on top of master (with the one easily resolvable conflict you had also noticed).

I think it can be pulled in cleanly now.

**Comment by jsandoe** [comment]
Reviewed yesterday's and today's commits. Everything looks very good.

**Pull request merged**
