### PR TITLE
Fixes bug where user can drag components under toolshelf

### PR DESCRIPTION
**Pull request by eireland**

### CODE REVIEW

**Review by kswenson — CHANGES_REQUESTED** [review]
The limit should be the top of the document, not the bottom of the tool shelf. If the document is scrolled, the user can place a tile behind the tool shelf (eventually the document should auto-scroll in this case).

**Review by tealefristoe — COMMENTED** [review]
Not sure if you're waiting on a review from me on this one. But I think you need to incorporate the y scroll of `.codap-container`, otherwise it's still not possible to drag to the top of the document when the document is scrolled down.

**Comment by eireland** [comment]
Current behavior is similar to V2.

**Review by kswenson — APPROVED** [review]
👍 Looks good -- I added a commit which takes into account the document scroll and changes the logic for finding the drag container.

**Pull request merged**
