### PR TITLE
More Undo/Redo

### PR DESCRIPTION
**Pull request by psndcsrv**
This has been rebased on the current master, so it includes the UI updates.

### CODE REVIEW

**Comment by bfinzer** [comment]
I’ll hopefully have time to go over this before a walkthrough I scheduled for 10 am on Monday.

**Comment by bfinzer** [comment]
Ok. I've been over the code. But I managed to schedule the review conflicting with another meeting. Ok if we review at 11 instead of 10?

Bill

**Comment by psndcsrv** [comment]
11 works for me. Talk to you then.

**Comment by bfinzer** [comment]
Aaron, can you resolve the conflicts?

**Comment by psndcsrv** [comment]
@bfinzer I've rebased the branch, so it will merge cleanly now.

**Comment by bfinzer** [comment]
Great. I should get to it soon.

Bill

**Comment by bfinzer** [comment]
Looks good!

**Pull request merged**
