### PR TITLE
Update logger url [#175337534] (master)

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by dougmartin** [comment]
**DO NOT MERGE**: need to wait until production log-ingester is adding ids to the logs.

**Review by kswenson — APPROVED** [review]
👍 LGTM

**Comment by dougmartin** [comment]
@kswenson Could you re-review this branch also?  Same change to hardcode https logger urls.

**Review by kswenson — APPROVED** [review]
👍 LGTM

**Pull request merged**
